/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Home {
  'title' : string,
  'heroImageId' : string,
  'subtitle' : string,
}
export interface Memory {
  'id' : string,
  'title' : string,
  'date' : string,
  'description' : string,
  'imageId' : string,
}
export interface Question {
  'id' : string,
  'questionText' : string,
  'category' : string,
}
export interface Theme {
  'backgroundColor' : string,
  'fontStyle' : string,
  'primaryColor' : string,
  'accentColor' : string,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'role' : string,
  'avatarImageId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'thumbnailImageId' : string,
  'description' : string,
  'videoUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemory' : ActorMethod<[Memory], undefined>,
  'addQuestion' : ActorMethod<[Question], undefined>,
  'addVideo' : ActorMethod<[Video], undefined>,
  'adminAddUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
  'adminDeleteUserProfile' : ActorMethod<[Principal], undefined>,
  'adminUpdateUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMemory' : ActorMethod<[string], undefined>,
  'deleteQuestion' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHome' : ActorMethod<[], Home>,
  'getMemories' : ActorMethod<[], Array<Memory>>,
  'getMemoryById' : ActorMethod<[string], Memory>,
  'getQuestionById' : ActorMethod<[string], Question>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getTheme' : ActorMethod<[], Theme>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getVideoById' : ActorMethod<[string], Video>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveHome' : ActorMethod<[Home], undefined>,
  'saveTheme' : ActorMethod<[Theme], undefined>,
  'updateMemory' : ActorMethod<[Memory], undefined>,
  'updateQuestion' : ActorMethod<[Question], undefined>,
  'updateVideo' : ActorMethod<[Video], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];