/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Memory = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'imageId' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'questionText' : IDL.Text,
  'category' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailImageId' : IDL.Text,
  'description' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'avatarImageId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Home = IDL.Record({
  'title' : IDL.Text,
  'heroImageId' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const Theme = IDL.Record({
  'backgroundColor' : IDL.Text,
  'fontStyle' : IDL.Text,
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemory' : IDL.Func([Memory], [], []),
  'addQuestion' : IDL.Func([Question], [], []),
  'addVideo' : IDL.Func([Video], [], []),
  'adminAddUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'adminDeleteUserProfile' : IDL.Func([IDL.Principal], [], []),
  'adminUpdateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMemory' : IDL.Func([IDL.Text], [], []),
  'deleteQuestion' : IDL.Func([IDL.Text], [], []),
  'deleteVideo' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHome' : IDL.Func([], [Home], ['query']),
  'getMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getMemoryById' : IDL.Func([IDL.Text], [Memory], ['query']),
  'getQuestionById' : IDL.Func([IDL.Text], [Question], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getTheme' : IDL.Func([], [Theme], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getVideoById' : IDL.Func([IDL.Text], [Video], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveHome' : IDL.Func([Home], [], []),
  'saveTheme' : IDL.Func([Theme], [], []),
  'updateMemory' : IDL.Func([Memory], [], []),
  'updateQuestion' : IDL.Func([Question], [], []),
  'updateVideo' : IDL.Func([Video], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Memory = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'imageId' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'questionText' : IDL.Text,
    'category' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailImageId' : IDL.Text,
    'description' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'avatarImageId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Home = IDL.Record({
    'title' : IDL.Text,
    'heroImageId' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const Theme = IDL.Record({
    'backgroundColor' : IDL.Text,
    'fontStyle' : IDL.Text,
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemory' : IDL.Func([Memory], [], []),
    'addQuestion' : IDL.Func([Question], [], []),
    'addVideo' : IDL.Func([Video], [], []),
    'adminAddUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'adminDeleteUserProfile' : IDL.Func([IDL.Principal], [], []),
    'adminUpdateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMemory' : IDL.Func([IDL.Text], [], []),
    'deleteQuestion' : IDL.Func([IDL.Text], [], []),
    'deleteVideo' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHome' : IDL.Func([], [Home], ['query']),
    'getMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getMemoryById' : IDL.Func([IDL.Text], [Memory], ['query']),
    'getQuestionById' : IDL.Func([IDL.Text], [Question], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getTheme' : IDL.Func([], [Theme], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getVideoById' : IDL.Func([IDL.Text], [Video], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveHome' : IDL.Func([Home], [], []),
    'saveTheme' : IDL.Func([Theme], [], []),
    'updateMemory' : IDL.Func([Memory], [], []),
    'updateQuestion' : IDL.Func([Question], [], []),
    'updateVideo' : IDL.Func([Video], [], []),
  });
};

export const init = ({ IDL }) => { return []; };